// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CryptoLockerDeFi"]: never
    ["IAavePool"]: never
    ["IUniswapV2Router02"]: never;
  }
}